apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt # it can be anything
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: teste@email.com
    privateKeySecretRef:
      name: letsencrypt-tls
    solvers:
    - http01:
      ingress:
        class: nginx
